// autogenerated code
class Call extends Object{
	public void main( String[] a) {
		System.out.println( new A(  ).go( 2674 ) );
	}
}
class A extends Object{
	public int go( int i) {
		return i  /  2;
	}
}
